### PR TITLE
Mark GMail Read: Compatibility with TB 102 revamped

### PR DESCRIPTION
**Pull request by peci1**
Hi, ATN did not like the previous approach of supporting 102, and it probably did not even actually work.

I found the time and converted it to a MailExtension without experiments, so it should (hope!) be the last update of this addon for a pretty long time! :)

I've changed the logic a bit so that now it does not depend on the names of the folders inside `[Gmail]`. Instead, it looks at the folder type. I've noticed that `All mail` and `Starred` do not have the type set, while all other folders do. So it seems safe to mark read all emails in (sub)folders in `[GMail]` that have a type set.

I also added a warning if the addon should mark more than 10 messages at a time - this should prevent unexpected behavior for people who have the addon installed, but forgot about it and got used to it not working. There is a way to get rid of this warning for good/until the end of the session.

I'll post it to ATN shortly.

### CODE REVIEW

**Comment by Qrzysio** [comment]
Awesome. Well done. 

I confirm the current version does not work. Looking forward for this PR to be merged!

**Comment by acabal** [comment]
Hi Martin, I think if you're going to be essentially remaking the addon, and setting yourself as the author in the metadata, it would be best if you simply forked it into your own repo and managed/supported it yourself. The license is GPLv3 so you're free to do that. Though it looks like you simply totally rewrote everything, so the license probably doesn't matter that much.

I haven't used Gmail in nearly a decade so I won't be updating or supporting this addon myself anymore; let alone being responsible for supporting something that I didn't write! :)

Good luck!

**Comment by peci1** [comment]
It's okay, Alex. I already have the fork and ATN releases are done from that. I just wanted the changes to reach back to you as the original author. If you don't like being updated about the addon anymore, I'll stop that ;)

Cheers!

Martin

**Comment by Qrzysio** [comment]
@acabal could you please let other people know about the new repository address. It might be a good idea to mark this repo as archived.

@peci1  I've already starred your repo ;) Please publish the add-on in the Mozilla market.

**Pull request closed without merging**
