### PR TITLE
[WIP] Hide Local Folders: Thunderbird 68 Support

### LINKED ISSUE #3: Thunderbird 68 support
Please add support for thunderbird 68

### PR DESCRIPTION
**Pull request by tooomm**
Fixes #3 

Credit goes to "Thomas S.": (Thanks @GaVenga for [linking](https://github.com/acabal/thunderbird-addons/issues/3#issuecomment-545295162))
https://www.thunderbird-mail.de/forum/thread/82781-lokaler-ordner-ausblenden/?postID=449334#post449334 (German)

As described in the [Thunderbird docs for updating extensions to 68 support](https://developer.thunderbird.net/add-ons/tb68), it's not advised to have both - old `install.rdf` and new `manifest.json`:
>Even though it is possible to have both install.rdf and manifest.json files in your extension, so you could release a version compatible with Thunderbird 60 and 68, it is not suggested for the following reasons: [...]

Therefore I only kept the new manifest.json.

The documents also says to bump the version to a new main one. That way one could release two separate versions for Thunderbird 60 and 68 - I went with v2.0 and kept the alpha:
>It is possible to maintain a legacy version and a WebExtension version of your add-on in parallel on ATN! You just need to use a higher major version number for the WebExtension version of your add-on and keep the old major version number when releasing a new legacy version. Basically releasing them in two different branches.

<br>

More information on converting a overlay type extension to a MailExtension with legacy support: https://developer.thunderbird.net/add-ons/tb68/overlays

<br>

---

<br>

## Important Open Questions ##
- [ ] Are there further adjustments needed? See this [help doc for changes to the TB core with v68](https://developer.thunderbird.net/add-ons/tb68/changes)

<br>

---

<br>

**This is untested and only copy pasted with the above mentioned tiny adjustments.
Please help to test and report back so that we can make the addon together compatible and ready for TB68 again!**

### CODE REVIEW

**Comment by Qrzysio** [comment]
Publishing a pull request without testing is not a good practice. You better open another issue and publish code there, or fork the repo, so I and other users will test it.

**Comment by tooomm** [comment]
My intention was to push things and therefore I thought it helps most if the process starts as the issue had no real activity.

Sadly, I've no environment setup for testing. However, this is reported to work. Otherwise there would be no reason to open a PR.
But other, more experienced people should look into (and double check) it as well first. Especially if they know the code a bit. I don't want to call it working without testing it for myself, therefore I let people transparently know and marked it as draft and work in progress.
The barrier is hopefully lower if one doesn't need to start from scratch: the important links are presented, and the most work is hopefully already done.

My fork can be found [here](https://github.com/tooomm/thunderbird-addons/tree/patch-1).

It would be very nice if you could give this a run as well and let us know how it goes!

**Comment by GaVenga** [comment]
This version (2.0a) works too -  tested with: manjaro linux

**Comment by acabal** [comment]
I'm not able to test this at the moment. Can anyone else test this to see if it works?

**Comment by acabal** [comment]
Actually I was able to test it and it works. Thanks!

I'll see if I can post this to the Mozilla addons site tonight, and if not tonight then tomorrow.

**Comment by tooomm** [comment]
Great! Thanks.

@acabal As you know your Addon code and functionality best... can you have a look at this link and see if there are further adjustments needed due to underlaying changes in TB, please: https://developer.thunderbird.net/add-ons/tb68/changes

**Pull request merged**
